export const TYPES = {
  authService: Symbol("authService"),
  contactFormService: Symbol("contactFormService"),
  notificationService: Symbol("notificationService"),
  blogService: Symbol("blogService"),
  courseService: Symbol("courseService"),
  paymentService: Symbol("paymentService"),
  userService: Symbol("userService"),
  orderService: Symbol("orderService"),
  encryptionService: Symbol("encryptionService"),
  localStorageService: Symbol("localStorageService"),
  dataStore: Symbol("dataStore"),
  blogStore: Symbol("blogStore"),
  cartStore: Symbol("cartStore"),
  courseStore: Symbol("courseStore"),
  paymentStore: Symbol("paymentStore"),
  userStore: Symbol("userStore"),
  uiStore: Symbol("uiStore"),
  adminUiStore: Symbol("adminUiStore"),
  rootStore: Symbol("rootStore"),
}
