export const TYPES = {
  authService: Symbol("authService"),
  contactFormService: Symbol("contactFormService"),
  notificationService: Symbol("notificationService"),
  blogService: Symbol("blogService"),
  courseService: Symbol("courseService"),
  paymentService: Symbol("paymentService"),
  dataStore: Symbol("dataStore"),
  blogStore: Symbol("blogStore"),
  courseStore: Symbol("courseStore"),
  paymentStore: Symbol("paymentStore"),
  userStore: Symbol("userStore"),
  uiStore: Symbol("uiStore"),
  adminUiStore: Symbol("adminUiStore"),
}
